### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by saradotramli** [synechron-finlabs/quorum-maker#21]
Don't see any activity for the past few months here. Though I do see a few new docker images getting published. Could you atleast let us know which docker image to use to upgrade to quorum 2.0?

**Comment by dhyansraj** [comment]
We are working on the new release that would have a lot more features to take development on Quorum to next level. Due to an architecture overhaul and additional components, the development is going on in a different repository that is not public yet. We are hoping to open it up by end of this month.
