### ISSUE TITLE
First node's IP is different from the tutorial

### ISSUE THREAD

**Issue by jgege** [synechron-finlabs/quorum-maker#42]
Hi,

I was setting up a network based on the tutorial in README.md. "Creating the first node" went on without any problems, I filled out the "form" using the exact data that was given in the tutorial including the IP address.

Then I went on to "Joining a Network", used the data that was given but it could not connect to the first node. It was a bit strange so I ran the following command to find the container's IP address:

docker inspect <first node's container id> | grep "IPAddress"

and it gave me this: 172.17.0.2 (instead of 10.0.2.15)

Any idea why it can't use the IP that I gave it?

BTW I'm using Manjaro Linux 17.1.11

**Comment by dhyansraj** [comment]
10.0.2.15 is my Virtual Machines IP where I was setting up multiple nodes. So you should use whatever IP of your computer. 172.17.0.2, 172.17.0.3, 172.17.0.4, etc are the IP addresses of default bridge network in Docker. So you can use this as well for networking the nodes. But it is strongly discouraged since they are dynamic IPs and could be changed each time you restart the container. If you are setting up multiple nodes on same box, please use the IP of eth0.

**Comment by jgege** [comment]
It does make sense :D I was thinking that would magically happen somehow :) Thanks for the quick reply
