### ISSUE TITLE
QM deploys 5 contracts immediately after docker-compose up

### ISSUE THREAD

**Issue by stefanionescu** [synechron-finlabs/quorum-maker#78]
I bootstrapped a 3 nodes development network, deployed some contracts to it and then executed 'docker-compose down'

After doing docker-compose up again, I see that there are a couple of contracts already deployed to the network without me doing anything.

Are these the contracts that I previously deployed, and if so, how do I cleanly start the network again after deploying contracts and bringing it down?

**Comment by dhyansraj** [comment]
QM internally uses a Node Manager Contract for storing the public keys of participant nodes and their other info. This is very much required to support some of the features of QM and you cant prevent it from getting deployed. This contract is deployed only one time and the rest of the transactions you see are each node registering their info in this contract. 

Due to the very immutability nature of blockchain, you cant undeploy/delete contracts or transactions from chain.

**Comment by stefanionescu** [comment]
So you say 6 deployed contracts are normal behaviour when starting up the network?

![quorum-6-contracts](https://user-images.githubusercontent.com/15263515/51575877-d7c89b00-1eab-11e9-9da0-2f69bbf790b5.png)

**Comment by stefanionescu** [comment]
Nevermind, now I got it
