### ISSUE TITLE
Restart quorum after vm resize

### ISSUE THREAD

**Issue by aroommen** [synechron-finlabs/quorum-maker#82]
I have a quorum blockchain already deployed with quorum maker and well into a 100 blocks and working in production. Now I need to resize my VM and subsequently need to restart all my processes including QM. How do I restart QM such that I retain all my blocks and continue from where I stopped the process before VM resize?

**Comment by colindog** [comment]
I also have ths question. I setup a 7 nodes dev net. After the server reset. I run docker-compose again.
But the blockhight is 0.

**Comment by dhyansraj** [comment]
@aroommen You shouldnt have any problem resizing the node unless the IP is not changed. You can start restart the node by going inside node directory and executing ./start.sh

Eg. cd node1 && ./start.sh

@colindog Do you see any errors in the log? Since you are running a dev network, IP change shouldn't matter. Please share more details, I can help you resolve.

**Comment by aroommen** [comment]
Thanks @dhyansraj for the prompt response. I was able to get it restarted after the resize without any hassles.
